---
label: Product
hide_body: true
display_field: name
fields:
- type: text
  name: name
  label: name
  config:
    required: true
- type: text
  name: price
  label: price
- type: text
  name: layout
  label: layout
  hidden: true
- name: category
  type: select
  default: []
  config:
    required: true
    options:
    - upgrade
    source:
      type: pages
      section: categories
      file: 
      path: 
  label: category
- name: image
  type: file
  config:
    maxSize: 64
  label: image
- name: description_markdown
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
  description: Описание продукта.
pages:
- _products/kabel-setevoy.md
