---
label: Product
hide_body: true
fields:
- type: text
  name: category
  label: category
- type: text
  name: name
  label: name
- type: text
  name: description_markdown
  label: description_markdown
- type: text
  name: price
  label: price
- type: text
  name: image
  label: image
- type: text
  name: layout
  label: layout
